name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-code:
    name: Test code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  test-action: # make sure the action works on a clean machine without building
    name: Test action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build --if-present
